---
title: "Explore Outcomes"
output: html_document
date: "2024-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

#source('FUNCTIONS/fxn_lag_master.R')


```

#read in file
```{r}
events2<-read_rds('Data/IntermediateFiles/events2.rds')%>%
  filter(!(is.na(bdat)))%>% 
  mutate(data_pull_date_min = min(date, na.rm = TRUE))%>%
  mutate(data_pull_date_max = max(date, na.rm = TRUE))%>%
  rowid_to_column()

```

#animals events
```{r}
#animals - eacy row is an animal------------
animals<-events2%>%
  group_by(animal_id, bdat, 
           source_farm, source_state, #optional
           data_pull_date_min, data_pull_date_max)%>%
  summarize(breed = paste0(sort(unique(breed)), collapse = ','))%>%
  ungroup()

#deads - each row is animal
deads<-events2%>%
  filter(Event == 'DIED')%>%
  group_by(animal_id)%>%
  summarize(date_died = min(date), 
            date_died_max = max(date))%>%
  distinct()%>%
  mutate(qc_date_died_diff = as.numeric(date_died_max-date_died))

#solds - each row is animal
solds<-events2%>%
  filter(Event == 'SOLD')%>%
  group_by(animal_id)%>%
  summarize(date_sold = min(date), 
            date_sold_max = max(date))%>%
  distinct()%>%
  mutate(date_sold_diff = as.numeric(date_sold_max-date_sold))

#------------------------------------------------
master_animals<-animals%>%
  left_join(solds)%>%
  left_join(deads)

write_rds(master_animals, 'Data/IntermediateFiles/master_animals.rds')

```

#animal lactation events
```{r}
#animal_lactations - each row is an animal/lactation----------
animal_lactations<-events2%>%
  group_by(animal_id, animal_id_lact, LACT)%>%
  summarize(date_lact_start = min(date), 
            date_lact_end = max(date))%>%
  ungroup()

#archives - each row is animal/lactation
archives<-events2%>%
  select(animal_id_lact, ardat)%>%
  distinct()%>%
  group_by(animal_id_lact)%>%
  summarize(date_archive = min(ardat), 
            date_archive_max = max(ardat))%>%
  distinct()%>%
  mutate(date_archive_diff = as.numeric(date_archive_max-date_archive))

#freshs - each row is animal/lactation------------
freshs<-events2%>%
  filter(Event == 'FRESH')%>%
  group_by(animal_id_lact)%>%
  summarize(date_fresh = min(date), 
            date_fresh_max = max(date))%>%
  distinct()%>%
  mutate(qc_date_fresh_diff = as.numeric(date_fresh_max-date_fresh))



#drys - each row is animal/lacatation
drys<-events2%>%
  filter(Event == 'DRY')%>%
  group_by(animal_id_lact)%>%
  summarize(date_dry = min(date), 
            date_dry_max = max(date))%>%
  distinct()%>%
  mutate(date_dry_diff = as.numeric(date_dry_max-date_dry))

#master animal_lactation events-----------------

master_animal_lactations<-animal_lactations%>%
  left_join(freshs)%>%
  left_join(drys)%>%
  left_join(archives)

write_rds(master_animal_lactations, 'Data/IntermediateFiles/master_animal_lactations.rds')

```

#health events
```{r}
#health events animal - each row is an animal  -------------------------
health_animal_level<-events2%>%
  filter(event_type %in% 'health')%>%
  filter(!(is.na(animal_id)))%>%
  filter(!(is.na(Event)))%>%
  arrange(animal_id, Event, date)%>%
  group_by(animal_id, Event)%>%
  mutate(event_ct_animal = 1:n(), 
         event_ct_animal_txt = paste0(Event, event_ct_animal)
         )%>%
  ungroup()%>%
  select(animal_id, date,  event_ct_animal_txt)%>%
  distinct()%>%
  pivot_wider(names_from = event_ct_animal_txt, 
              values_from = date)%>%
  distinct()

write_rds(health_animal_level, 'DATA/IntermediateFiles/health_animal_level.rds')


#health events animal_lactation - each row is animal/lactation
health_lactation_level<-events2%>%
  filter(event_type %in% 'health')%>%
  arrange(animal_id_lact, Event, date)%>%
  group_by(animal_id_lact, Event)%>%
  mutate(event_ct_animal_lact = 1:n(), 
         event_ct_animal_lact_txt = paste0(Event, event_ct_animal_lact) 
         )%>%
  ungroup()%>%
  select(animal_id_lact, date,  event_ct_animal_lact_txt)%>%
  distinct()%>%
  pivot_wider(names_from = event_ct_animal_lact_txt, 
              values_from = date)

write_rds(health_lactation_level, 'DATA/IntermediateFiles/health_lactation_level.rds')

```


#custom important events------------------------

```{r}
arrives_pot<-events2%>%
  filter(Event == 'ARVDPOT')%>%
  group_by(animal_id)%>%
  summarize(date_arrived_pot = min(date), 
            date_arrived_pot_max = max(date))%>%
  distinct()%>%
  mutate(date_arrived_pot_diff = as.numeric(date_arrived_pot_max-date_arrived_pot))


arrives_kdd<-events2%>%
  filter(Event == "ARVKDD")%>%
  group_by(animal_id)%>%
  summarize(date_arrived_kdd = min(date), 
            date_arrived_kdd_max = max(date))%>%
  distinct()%>%
  mutate(date_arrived_kdd_diff = as.numeric(date_arrived_kdd_max-date_arrived_kdd))


assists<-events2%>%
  filter(Event == "ASSIST")%>%
  group_by(animal_id)%>%
  summarize(date_assist = min(date), 
            date_assist_max = max(date))%>%
  distinct()%>%
  mutate(date_assist_diff = as.numeric(date_assist_max-date_assist))


#-------------------------
custom_animal_events<-animals%>%
  left_join(arrives_pot)%>%
  left_join(arrives_kdd)%>%
  left_join(assists)
write_rds(custom_animal_events, 'Data/IntermediateFiles/custom_animal_events.rds')

```

